languageCode = "en-us"
title = "Dunst"
baseurl = "https://dunst-project.org"
theme = "liquorice"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
	style = 'bw'
